//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Diet')
export class DietEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  Description: string;

  @Column('text', { nullable: true })
  Type: string;

  @Column('text', { nullable: true })
  Goal: string;

  @Column('integer', { nullable: true })
  Calories: number;

  @Column('real', { nullable: true })
  Proteins: number;

  @Column('real', { nullable: true })
  Fats: number;

  @Column('real', { nullable: true })
  Carbohydrates: number;

  @Column('text', { nullable: true })
  Duration: string;
}
