//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Exercise')
export class ExerciseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  Description: string;

  @Column('text', { nullable: true })
  MuscleGroup: string;

  @Column('text', { nullable: true })
  DifficultyLevel: string;

  @Column('text', { nullable: true })
  EquipmentNeeded: string;

  @Column('text', { nullable: true })
  Duration: string;

  @Column('integer', { nullable: true })
  Repetitions: number;

  @Column('integer', { nullable: true })
  Sets: number;
}
