//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Diet: {
      name: 'Diet',
      fields: {
        Name: 'Name',
        Description: 'Description',
        Type: 'Type',
        Goal: 'Goal',
        Calories: 'Calories',
        Proteins: 'Proteins',
        Fats: 'Fats',
        Carbohydrates: 'Carbohydrates',
        Duration: 'Duration',
        id: 'id',
      },
    },
    Exercise: {
      name: 'Exercise',
      fields: {
        Name: 'Name',
        Description: 'Description',
        MuscleGroup: 'Muscle Group',
        DifficultyLevel: 'Difficulty Level',
        EquipmentNeeded: 'Equipment Needed',
        Duration: 'Duration',
        Repetitions: 'Repetitions',
        Sets: 'Sets',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Diet: {
      name: 'Diet (fr)',
      fields: {
        Name: 'Name (fr)',
        Description: 'Description (fr)',
        Type: 'Type (fr)',
        Goal: 'Goal (fr)',
        Calories: 'Calories (fr)',
        Proteins: 'Proteins (fr)',
        Fats: 'Fats (fr)',
        Carbohydrates: 'Carbohydrates (fr)',
        Duration: 'Duration (fr)',
        id: 'id',
      },
    },
    Exercise: {
      name: 'Exercise (fr)',
      fields: {
        Name: 'Name (fr)',
        Description: 'Description (fr)',
        MuscleGroup: 'Muscle Group (fr)',
        DifficultyLevel: 'Difficulty Level (fr)',
        EquipmentNeeded: 'Equipment Needed (fr)',
        Duration: 'Duration (fr)',
        Repetitions: 'Repetitions (fr)',
        Sets: 'Sets (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
